### ISSUE TITLE
Which libary to use for displaying models? 

### ISSUE THREAD

**Issue by stockto2** [stockto2/desktophero#2]
What should we use for the character view part of the app, the part that displays the 3D models? Here are some options:

1. **Three.JS** - 
Looks like it can do everything we want, is simple and lightweight, but in my experience so far it's hard to find good documentation. 
2. **Blend4Web** - 
Looks pretty, might have good documentation, and which we can use for free since the project is open source. 

Anyone have experience with either of these technologies? 

Some things to consider: 
* Documentation - will it be easy to find out how to do what we want? 
* Compatibility - what browsers/systems will it work on?
* Licenses - what licences do we adopt by using these libraries?

**Comment by thetrebor** [comment]
I've heard of Three.JS and dabbled with it very briefly.
Here is a beginners guide:  http://blog.teamtreehouse.com/the-beginners-guide-to-three-js
And here are some brunch skeletons that get you past initial setup:
https://github.com/Jeremboo/brunch-threejs-es2015
https://github.com/vdaguenet/threejs-starter-kit

This is just with a couple minutes searching.  

Three.js seems to support server side and client side and is platform agnostic.  It uses the MIT licenses which means you can repackage it commercially as long as you include the MIT license text and declare the use of the library.

**Comment by stockto2** [comment]
We will use Three.JS since it is simpler and used more widely.
