### ISSUE TITLE
What technology to use for server/client?

### ISSUE THREAD

**Issue by stockto2** [stockto2/desktophero#3]
I have experience with GWT. Seems like it would work fine to create the server and client. Code is all in Java. 

Pros:

- I know how to use it already, could create something fast

Cons:

- Not lightweight
- Harder to pick up if you don't know how it works. 

Anyone have web experience with other technologies? What do you use?

**Comment by thetrebor** [comment]
I've used nodewebkit (now NW) for desktop apps, if you wanted this to be open source desktop binary with a cloud based distributed model library.  Basically the entire thing would be javascript/node.  
I'm a LAMP guy myself so i tend towards PHP, perl, Python, or Ruby.  Also this greatly simplifies deployments since java requires substantial extra steps for integration and deployment.

Are there any libraries that you need straight off that are language dependent?

**Comment by whitecat** [comment]
I really do not like GWT. A couple of cons I can think of is: Google has dropped support of GWT and will no longer actively updates it. Also control  of the Javascript is lost, as it is all in Java.

I like Angular as it is simple to use, and based in Javascript. 
Pro:
Easy to understand and program in
Lots of other frameworks, and libraries build on Angular and Node JS

Con:
Angular 2 is being released and it is a complete rewrite of Angular
Angular might not be updated often

I also do wouldn't mind Django as it it python based and pretty easy to pickup.

I echo what @thetrebor said what libraries on GWT do you have in mind?

**Comment by thetrebor** [comment]
Angular is popular and the v1 of the framework will continue to have large support long after v2 is finalized.  They're essentially apples and oranges anyway.  I'm a curmudgeon and don't like Angular for "kids, get off my damn lawn" reasons, but it's a realistic framework that's does real work for people in the real world every day.  bonus points, it can also be packaged as with NW (node-webkit) to make a slick desktop app.  IIRC that's what PopcornTime did.

**Comment by stockto2** [comment]
The only library I have in mind at the moment that we would need to use is Three.js. 

Hmm, if GWT isn't supported anymore, it might not be good for a potentially long-term project. I'm looking into Angular and Django now to see if they look like they will fit the project well and be quickish to pick up.

**Comment by thetrebor** [comment]
I vote node/angular although django is also quite good. Also my team knows
both so I can ask questions or encourage them to contribute.

**Comment by stockto2** [comment]
Alrighty. Since the project is open source now, I think it will be worthwhile to forgo using GWT and spend some time picking up some of these more common frameworks.

thetrebor has recommended a combination of PHPSlim and either KnockoutJS or AngularJS. I'm going to go through some tutorials and try things out to pick up the basics.
