### ISSUE TITLE
SQL Schema Fixes

### ISSUE THREAD

**Issue by utdrmac** [stockto2/desktophero#8]
Side note: I hate git's nature of forcing you to fork your own copy just to make one-off pull-requests. Hence, the following long post.

As a MySQL Architect for [Percona](http://www.percona.com), and a [campaign backer](https://www.kickstarter.com/profile/1453742700) I've read over your schema and there's a few common errors that I see in just about every client that I deal with.

Before we get started, your sample schema shows MySQL 5.5. The 5.5.* series is at least 5 years old. MySQL 5.7 is the current standard and you should be coding against this version. `brew install mysql` should give you the latest 5.7 community version.

### accounts. sql
`account_id` should be unsigned and PRIMARY KEY
`user_id` should also be unsigned (unless you plan to have negative ids)
varchar(255) --> who has a first name or a last name that's 255 characters long?
What's the difference between account_id and user_id? Which one will be searched by more often? That one should be primary key and the other should have an index.

### sessions.sql
A `PRIMARY KEY` should never be a string-based field in MySQL. There's [plenty of background](https://www.percona.com/blog/2015/04/03/illustrating-primary-key-models-in-innodb-and-their-impact-on-disk-usage/) information if you want to read up on why.
In MySQL 5.7, you can make `session_data` a JSON column type, which stores better on-disk than "text" (assuming you are using JSON to hold session data, which you should be in PHP when serializing objects).
Using CRC32() on the token as the PRIMARY KEY will produce integer-based keys and still allow for searchable tokens.

### users.sql
UNSIGNED on the PK. email address 255 characters? I hope pass_phrase is technically the hash of the user's password. You should not store plain-text passwords; always calculate (SHA256) and store the hash. Do hash-hash comparisons. There are plenty of client-side calculators.

### sample.sql
I realize this is a "sample" but I wanted to point out one more thing, just in case.
Several tables have both a `PRIMARY KEY` and a `UNIQUE KEY`. A `PRIMARY KEY` implies uniqueness. Having both indexes on the same column produces two separate indexes with exactly the same contents. And because all secondary keys contain a copy of the PRIMARY KEY, your UNIQUE KEY is actually a 2x repeated PRIMARY KEY. You should remove the `UNIQUE` indexes.

**Comment by stockto2** [comment]
Hey Matthew, thanks for the observations! 
Maybe @thetrebor can look at this one and see what we want to do here.

**Comment by thetrebor** [comment]
@utdrmac the current schema is throw away.  it's cribbed from an old project where the client didn't pay.  my next tasks are to make it rational and pertinent to this project.  It was going to inherit data from a very old Oracle db for an insurance aggregator so there were all sorts of sins in the schema that made sense for the use cases but which are silly for real life.

**Comment by utdrmac** [comment]
I look forward to the new schema and offer my assistance where I can.
