### ISSUE TITLE
Mesh problems

### ISSUE THREAD

**Issue by unkbar** [stockto2/desktophero#80]
The default man with the sword that comes up when I open the page is only 8mm high. I see there's a "Size, Print, Material" button that is not yet implemented.  So I tried to use Meshmixer to scale it up to 35mm. 
I can scale it there fine, but when I use Meshmixer's Analysis->Inspector function, it highlights a lot of problems, mostly in the hands.  When i tell it to Auto Repair them, the hands disappear.  Erasing the hands may be a Meshmixer problem, but you should look into the mesh defects in the exported model.  I'm going to try to print the scaled model anyway.  Sorry if this is naive, but I'm a gamer, not a designer and this is all new to me.

**Comment by ahdchild** [comment]
I found mesh problems too. In meshmixer, I used Edit->Make Solid to fix them. I would resize first

**Comment by stockto2** [comment]
Will make DH export larger figures by default. Your printer
