### ISSUE TITLE
Export to STL fails in Safari

### ISSUE THREAD

**Issue by scooper4711** [stockto2/desktophero#90]
# Steps to recreate
1. Running Mac OS 10.12.3 (latest version as of ticket creation)
2. Running Safari 10.0.3 (also latest)
3. Open DesktopHero.com and log in
4. Press "download to STL" on default figure
5. Nothing happens.

# Expected results
- STL file downloads

# Workaround
- Use Chrome on the same machine.

**Comment by stockto2** [comment]
Thanks for pointing this out!

**Comment by stockto2** [comment]
See https://github.com/stockto2/desktophero/blob/f1f611b2a9051f934e67cf7ebc610fc287508204/htdocs/js/SceneView.js#L138
and 
https://github.com/stockto2/desktophero/blob/9de23c7c77133dc50c1b2c38280bcff4aea06279/htdocs/js/FileSaver.js#L5

Something here must not work with Safari.

**Comment by scooper4711** [comment]
Works now.
